Fixes #55: Deploy client to vercel

diff --git a/.github/workflows/client-ci-cd.yaml b/.github/workflows/client-ci-cd.yaml
--- a/.github/workflows/client-ci-cd.yaml
+++ b/.github/workflows/client-ci-cd.yaml
@@ -1,38 +1,110 @@
-name: Deploy to cloudflare
+name: client-ci-cd
 on:
   push:
     branches:
-      - '**'
+      - '*'
+    paths:
+      - 'client/**'
+  pull_request:
+    branches:
+      - develop
+      - main
+      - develop-snapshot
+    paths:
+      - 'client/**'
+
 jobs:
-  deploy-client:
-    name: Deploy client to cloudflare
+  # web-lint:
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       working-directory: client
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '18'
+  #     - name: Install dependencies
+  #       run: npm install
+  #     - name: Run ESLint
+  #       run: npm run lint
+  #     - name: Check for ESLint errors
+  #       if: ${{ failure() }}
+  #       run: echo "ESLint failed!" && exit 1
+
+  test-and-build:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: client
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '18'
+      - name: Install dependencies
+        run: npm install
+      # - name: Run Unit Tests
+      #   run: npm test -- --passWithNoTests
+      # - name: Check for test errors
+      #   if: ${{ failure() }}
+      #   run: echo "Tests failed!" && exit 1
+      - name: Build the application
+        run: npm run build
+      - name: Verify Build Output
+        run: ls -l .next || { echo "Build output (.next) not found!"; exit 1; }
+      - name: Upload Build Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: web-build
+          include-hidden-files: 'true'
+          path: ${{ github.workspace }}/client/.next
+          if-no-files-found: error
+
+  deploy-to-vercel:
+    env:
+      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
+      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_CLIENT_PROJECT_ID }}
+    needs: test-and-build
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
+      - uses: actions/checkout@v4
         with:
-          node-version: '20'
-          cache: 'npm'
-          cache-dependency-path: client/package-lock.json
-
-      - name: Install Dependencies
-        working-directory: ./client
-        run: npm ci
-
-      - name: Build
-        working-directory: ./client
-        run: npm run build
-        env:
-          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
-
-      - name: Deploy
-        uses: cloudflare/wrangler-action@v3
+          fetch-depth: 0
+      - uses: actions/setup-node@v4
         with:
-          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
-          command: pages deploy ./client/out --project-name=intellics
-          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
+          node-version: '18'
+      - name: Install Vercel CLI
+        run: npm install -g vercel@latest
+      - uses: actions/download-artifact@v4
+        with:
+          name: web-build
+          path: ${{ github.workspace }}/client/.next
+      - name: set Vercel environment
+        id: vercel-env
+        run: |
+          if [ "${{github.ref}}" = "refs/heads/main" ]; then
+            echo "env=production" >> $GITHUB_OUTPUT
+          else
+            echo "env=preview" >> $GITHUB_OUTPUT
+          fi
+      - name: Pull vercel environment information 
+        run: |
+          cd client
+          vercel pull --yes --environment=${{ steps.vercel-env.outputs.env }} --token=${{ secrets.VERCEL_TOKEN }}
 
+      - name: Deploy to vercel (production)
+        if: github.ref == 'refs/heads/main'
+        run: |
+          cd client
+          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
+
+      - name: Deploy to vercel (preview)
+        if: github.ref != 'refs/heads/main'
+        run: |
+          cd client
+          vercel deploy --token ${{ secrets.VERCEL_TOKEN }}
